// Command recognise builds and queries text recognition trees.
//
// Modes:
//
//	recognise -train  -corpus ./texts -memory ./recog_db
//	recognise -detect -memory ./recog_db -sample ./input.txt
//	recognise -fingerprint -model chatgpt -corpus ./chatgpt_texts -memory ./recog_db
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"strings"

	"github.com/mlekudev/dendrite/pkg/cayley"
	"github.com/mlekudev/dendrite/pkg/detect"
	"github.com/mlekudev/dendrite/pkg/extract"
	"github.com/mlekudev/dendrite/pkg/hadamard"
	"github.com/mlekudev/dendrite/pkg/memory"
	"github.com/mlekudev/dendrite/pkg/train"
)

func main() {
	var (
		trainMode   = flag.Bool("train", false, "train baseline tree from corpus directory")
		detectMode  = flag.Bool("detect", false, "detect AI text in a sample")
		fingerprint = flag.Bool("fingerprint", false, "build model fingerprint from labeled corpus")

		corpusDir   = flag.String("corpus", "", "corpus directory (for -train and -fingerprint)")
		memoryDir   = flag.String("memory", ".recognise_db", "persistent memory directory")
		trollMemory = flag.String("troll-memory", "", "badger DB with manipulation-trained snapshot (for -detect)")
		sampleFile  = flag.String("sample", "", "text file to analyze (for -detect)")
		modelName   = flag.String("model", "", "model name (for -fingerprint)")
		window      = flag.Int("window", 500, "max tokens to process per sample (0=unlimited)")
	)

	flag.Parse()

	ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
	defer cancel()

	modeCount := 0
	if *trainMode {
		modeCount++
	}
	if *detectMode {
		modeCount++
	}
	if *fingerprint {
		modeCount++
	}
	if modeCount != 1 {
		fmt.Fprintln(os.Stderr, "exactly one of -train, -detect, -fingerprint required")
		flag.Usage()
		os.Exit(1)
	}

	switch {
	case *trainMode:
		if *corpusDir == "" {
			log.Fatal("-corpus required for -train mode")
		}
		if err := runTrain(ctx, *corpusDir, *memoryDir); err != nil {
			log.Fatal(err)
		}

	case *detectMode:
		if *sampleFile == "" {
			log.Fatal("-sample required for -detect mode")
		}
		if err := runDetect(ctx, *sampleFile, *memoryDir, *trollMemory, *window); err != nil {
			log.Fatal(err)
		}

	case *fingerprint:
		if *corpusDir == "" || *modelName == "" {
			log.Fatal("-corpus and -model required for -fingerprint mode")
		}
		if err := runFingerprint(ctx, *corpusDir, *memoryDir, *modelName); err != nil {
			log.Fatal(err)
		}
	}
}

// runTrain builds a Cayley tree from a human text corpus.
// The tree captures the word-length distribution and structural patterns
// of human-written text across 8 depth levels.
func runTrain(ctx context.Context, corpusDir, memoryDir string) error {
	db, err := memory.Open(memoryDir)
	if err != nil {
		return fmt.Errorf("open memory: %w", err)
	}
	defer db.Close()

	tree := cayley.NewTree()
	cfg := train.DefaultConfig()

	registry := extract.NewRegistry()
	files, err := collectFiles(corpusDir)
	if err != nil {
		return fmt.Errorf("walk corpus: %w", err)
	}

	fmt.Printf("=== training Cayley tree (z=8, depth 8) ===\n")
	fmt.Printf("corpus: %d files from %s\n", len(files), corpusDir)

	for i, path := range files {
		select {
		case <-ctx.Done():
			fmt.Println("\ninterrupted, saving progress...")
			goto save
		default:
		}

		rc, err := registry.Extract(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  skip %s: %v\n", path, err)
			continue
		}

		_, err = train.FromReader(ctx, tree, rc, cfg)
		rc.Close()
		if err != nil {
			fmt.Fprintf(os.Stderr, "  error %s: %v\n", path, err)
			continue
		}

		// Snapshot root Walsh for convergence tracking at file boundaries.
		tree.RecordHistory()

		if (i+1)%100 == 0 || i == len(files)-1 {
			h := tree.Health()
			fmt.Printf("  [%d/%d] tokens=%d rootDC=%d converged=%v\n",
				i+1, len(files), h.TokenCount, h.RootWalsh[0], h.Converged)
		}

		if train.IsConverged(tree, cfg) {
			tree.Converged = true
			fmt.Printf("  converged at file %d/%d\n", i+1, len(files))
			break
		}
	}

save:
	// Freeze and save the tree.
	snap := cayley.Freeze(tree)
	data, err := json.Marshal(snap)
	if err != nil {
		return fmt.Errorf("marshal snapshot: %w", err)
	}
	if err := db.RecordMindsicle(1, data); err != nil {
		return fmt.Errorf("save snapshot: %w", err)
	}

	fmt.Printf("\n=== training complete ===\n")
	fmt.Printf("total tokens: %d\n", tree.TokenCount)
	fmt.Printf("snapshot: %d bytes\n", len(data))

	// Print per-level Walsh info.
	for d := range cayley.MaxDepth {
		stats := tree.StatsAt(d)
		passNum := cayley.MaxDepth - d
		dc := stats.Walsh[0]
		detail := hadamard.DetailEnergy(stats.Walsh)
		fmt.Printf("  level %d (pass %d): DC=%d detail=%d\n", d, passNum, dc, detail)
	}

	return nil
}

// runDetect tests whether sample text was AI-generated by probing it
// against a trained Cayley tree.
func runDetect(ctx context.Context, sampleFile, memoryDir, trollMemoryDir string, tokenWindow int) error {
	detector, err := detect.NewDetector(memoryDir, tokenWindow)
	if err != nil {
		return fmt.Errorf("load detector: %w", err)
	}

	if trollMemoryDir != "" {
		if err := detector.LoadTrollTree(trollMemoryDir); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not load troll tree: %v\n", err)
		}
	}

	content, err := os.ReadFile(sampleFile)
	if err != nil {
		return err
	}

	fmt.Printf("sample: %s (%d bytes)\n", sampleFile, len(content))

	verdict := detector.Detect(ctx, string(content))
	fmt.Println()
	fmt.Print(verdict.String())

	return nil
}

// runFingerprint builds an author-specific Cayley tree from labeled corpus.
// The origin channel captures the author's characteristic patterns.
func runFingerprint(ctx context.Context, corpusDir, memoryDir, modelName string) error {
	db, err := memory.Open(memoryDir)
	if err != nil {
		return fmt.Errorf("open memory: %w", err)
	}
	defer db.Close()

	tree := cayley.NewTree()
	cfg := train.DefaultConfig()
	cfg.AuthorID = modelName

	registry := extract.NewRegistry()
	files, err := collectFiles(corpusDir)
	if err != nil {
		return fmt.Errorf("walk corpus: %w", err)
	}

	fmt.Printf("fingerprinting model %q from %d files\n", modelName, len(files))

	for i, path := range files {
		select {
		case <-ctx.Done():
			fmt.Println("\ninterrupted, saving progress...")
			goto save
		default:
		}

		rc, err := registry.Extract(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "  skip %s: %v\n", path, err)
			continue
		}

		_, err = train.FromReader(ctx, tree, rc, cfg)
		rc.Close()
		if err != nil {
			fmt.Fprintf(os.Stderr, "  error %s: %v\n", path, err)
			continue
		}

		if (i+1)%100 == 0 || i == len(files)-1 {
			fmt.Printf("  [%d/%d] tokens=%d\n", i+1, len(files), tree.TokenCount)
		}
	}

save:
	snap := cayley.Freeze(tree)
	data, err := json.Marshal(snap)
	if err != nil {
		return fmt.Errorf("marshal snapshot: %w", err)
	}
	if err := db.RecordMindsicle(1, data); err != nil {
		return fmt.Errorf("save snapshot: %w", err)
	}

	fmt.Printf("\n%s fingerprint: %d tokens, origin=%v\n",
		modelName, tree.TokenCount, tree.OriginProfile)

	// Print Walsh balance.
	rootWalsh := tree.RootWalsh()
	dc := rootWalsh[0]
	if dc < 0 {
		dc = -dc
	}
	detail := hadamard.DetailEnergy(rootWalsh)
	total := dc + detail
	if total > 0 {
		balance := float64(detail) / float64(total)
		fmt.Printf("Walsh balance: %.4f (higher = more human-like variation)\n", balance)
	}

	return nil
}

// collectFiles recursively collects file paths from a directory.
func collectFiles(dir string) ([]string, error) {
	var files []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			if strings.HasPrefix(info.Name(), ".") && info.Name() != "." {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasPrefix(info.Name(), ".") || info.Size() < 100 {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

